version: "3"
services:
  api:
    image: eu.gcr.io/planar-acronym-293718/api:latest
  client:
    image: eu.gcr.io/planar-acronym-293718/client:latest
    environment:
      - REACT_APP_API_BASE_URL=http://proxy
  proxy:
    restart: always
    image: eu.gcr.io/planar-acronym-293718/proxy:latest
    ports:
      - "8080:80"
    depends_on:
      - api
      - client
  test:
    image: eu.gcr.io/planar-acronym-293718/test:latest
    depends_on:
      - api
      - client
      - proxy
