version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - /app/dist
      - ./api:/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
  proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "8080:80"
    depends_on:
      - api
      - client
  test:
    build:
      dockerfile: Dockerfile
      context: ./test
    volumes:
      - /app/node_modules
      - ./test:/app
    depends_on:
      - api
      - client
      - proxy
